spring.application.name=Galeria

# ==============================================================
# 1. CONFIGURACIÓN DEL SERVIDOR
# ==============================================================
# Puerto donde correrá la API de Spring Boot
server.port=8080

# ==============================================================
# 2. CONEXIÓN A LA BASE DE DATOS POSTGRESQL (DOCKER)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5332/museo_db
spring.datasource.username=Miguel
# contraseña del  contenedor de Docker
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# 3. CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================================================
# 'none' le dice a Spring Boot que NO cree las tablas
# automáticamente, sino con un  script SQL propio.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring las consultas SQL que se ejecutan
spring.jpa.show-sql=true

# Le da un formato bonito y legible al SQL en la consola
spring.jpa.properties.hibernate.format_sql=true

# Le indica a Hibernate qué dialecto de SQL usar (optimizado para Postgres)

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Para evitar problemas con la carga de objetos pesados (Lazy Loading)
spring.jackson.serialization.fail-on-empty-beans=false