###Prueba para obtener todas las obras
GET http://localhost:8080/api/arts


###prueba de creacion de usuario
POST http://localhost:8080/api/buyers/register
Content-Type: application/json

{
  "nombre": "rhixeidys",
  "apellido": "Usuario",
  "login": "rhixeidys01",
  "password": "password123",
  "email": "rhixeidys@test.com",
  "telefono": "04141234567",
  "direccionEnvio": "Ciudad Guayana, Bolivar",
  "datosTarjetaMask": "4540-XXXX-XXXX-1234"
}

###Prueba para pagar membresia
POST http://localhost:8080/api/buyers/1/pay-membership
Content-Type: application/json

{
  "metodoPago": "Tarjeta de Crédito"
}

### Obtener todos los compradores (Para ver si Miguel tiene su código)
GET http://localhost:8080/api/buyers


###prueba de Recuperacion de codigo
### Escenario 1: Recuperación Exitosa
POST http://localhost:8080/api/buyers/recover-code
Content-Type: application/json

{
  "email": "rhixeidys01@test.com",
  "respuestas": ["Bobby", "caracas", "escuela bolivar"]
}

### Escenario 2: Error por respuestas incorrectas
POST http://localhost:8080/api/buyers/recover-code
Content-Type: application/json

{
  "email": "rhixeidys01@test.com",
  "respuestas": ["Gato", "Error", "Falso"]
}

###Prueba e Login
POST http://localhost:8080/api/buyers/login
Content-Type: application/json

{
  "login": "miguel01",
  "password": "password123"
}


###Prueba para comprar la primera obra
POST http://localhost:8080/api/orders/purchase

{
  "obraId": 1,
  "compradorId": 1,
  "adminId": 2,
  "metodoPago": "Transferencia Bancaria",
  "direccionEnvio": "Av. Principal, Edif. Galería, Apto 4B"
}