###Prueba para obtener todas las obras
GET http://localhost:8080/api/arts


###prueba de creacion de usuario
POST http://localhost:8080/api/buyers/register
Content-Type: application/json

{
  "nombre": "Miguel",
  "apellido": "Usuario",
  "login": "manuel01",
  "password": "password123",
  "email": "miguel@test.com",
  "telefono": "04141234567",
  "direccionEnvio": "Ciudad Guayana, Bolivar",
  "datosTarjetaMask": "4540-XXXX-XXXX-1234"
}

###Prueba para pagar membresia
POST http://localhost:8080/api/buyers/2/pay-membership
Content-Type: application/json

{
  "metodoPago": "Tarjeta de Crédito"
}